/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountMenu: typeof import('./components/AccountMenu.vue')['default']
    AppFooter: (typeof import("./components/AppFooter.vue"))["default"]
    CartItem: typeof import('./components/CartItem.vue')['default']
    CategoryItem: typeof import('./components/CategoryItem.vue')['default']
    GradientButton: typeof import('./components/GradientButton.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    NavDrawer: typeof import('./components/NavDrawer.vue')['default']
    NumberInput: typeof import('./components/NumberInput.vue')['default']
    Product: typeof import('./components/Product.vue')['default']
    ProductSkeleton: typeof import('./components/ProductSkeleton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/SearchBar.vue')['default']
    ShoppingCart: typeof import('./components/ShoppingCart.vue')['default']
  }
}
