/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: (typeof import("./components/AppFooter.vue"))["default"]
    GradientButton: typeof import('./components/GradientButton.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    NavDrawer: typeof import('./components/NavDrawer.vue')['default']
    Product: typeof import('./components/Product.vue')['default']
    ProductSkeleton: typeof import('./components/ProductSkeleton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
